In [9]:
#decoding: utf-8
#encoding: utf-8

#openCV transform C++ code to python
import cv2 as cv
from imutils import paths
import os

path="~/Desktop/a/2.jpg"
name=os.path.split(path)[]
print name



2.jpg


In [ ]:
#encoding:utf-8  
import cv2  
img=cv2.imread("./1.jpg")  
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)  
#gray=cv2.GaussianBlur(gray, (3, 3), 0)  
#gray=cv2.Canny(gray,100,300)  
ret, binary = cv2.threshold(gray,127,255,cv2.THRESH_BINARY)  

binary,contours,hierarchy= cv2.findContours(binary,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)  
cv2.drawContours(img,contours,-1,(0,0,255),3)  
#print(contours[0])  
cv2.imshow("0",binary)  
#cv2.imshow("win10",img)  
cv2.waitKey(0)  


In [ ]:
import cv2  
import numpy as np 
img = cv2.imread('./1.png')  
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
ret, binary = cv2.threshold(gray,127,255,cv2.THRESH_BINARY)  
  
binary,contours, hierarchy = cv2.findContours(binary,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)  
#print contours
contours_update=[]

N= np.array(contours).shape[0]
update=[]
#cv2.drawContours(img,contours,-1,(0,255,0),3) 

rect = cv2.minAreaRect(contours[1])
update.append(contours[1])
contours_update.append(rect)
box = cv2.boxPoints(rect)

box = np.int0(box)
cv2.drawContours(img, [box], 0, (0, 0,255), 3)
print box
points=box
left_min=min(points[0][0],points[1][0],points[2][0],points[3][0])
right_max=max(points[0][0],points[1][0],points[2][0],points[3][0])
up_max=max(points[0][1],points[1][1],points[2][1],points[3][1])
down_min=min(points[0][1],points[1][1],points[2][1],points[3][1])
CutImage=img[down_min:up_max,left_min:right_max]
img=CutImage
print left_min,right_max,down_min,up_max
#image=cv2.resize(img,(450,900),interpolation=cv2.INTER_AREA)

#print update
cv2.imshow('', img)
cv2.waitKey(0)# the number of windows

In [11]:
import cv2  
import numpy as np 
img = cv2.imread('./1.png')  
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
M=np.mat(gray)
print M
print  M.getA()

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [51]:
#encoding:utf-8  
import cv2  
import numpy as np
res=[]

img=cv2.imread("./1.jpg") 
res.append(img)
a=np.array(res)
print a.shape
res.append(img)
b=np.array(res)
print b.shape

(1, 540, 864, 3)
(2, 540, 864, 3)


In [13]:
#coding: utf-8

#Laplace

import cv2 
import numpy as np

def show(image,name):
    cv2.imshow('%s'%name,image)
    cv2.waitKey(0)

    
def save_image(image,name):
    path_out=path+name+'.jpg'
    cv2.imwrite(path_out,image)

def Edge(path):#should input binary image
    #calculation
    image=cv2.imread(path,cv2.CV_8UC1) 
    binary,contours, hierarchy = cv2.findContours(image,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_NONE) 
    #in open CV3， findContours return 3 value; so my version is openCV3

    #draw boundary on the image
    image=cv2.drawContours(image,contours,-1,(0,0,255),3)#-1:draw all edge;  3:line width；（0，0，255):RGB color scaler
    image_Edge=image
    return image_Edge,contours #outpur contours is a array,

#不相连的轮廓求最小外界矩形,并添加到原图中
def draw_Min_Rect(image,contours):
    N= np.array(contours).shape[0]
    for i in range (0,N):
        min_=cv2.minAreaRect(contours[i])
        box = cv2.boxPoints(min_) 
        box = np.int0(box)
        cv2.drawContours(image, [box], 0, (0,0,255), 3)
    #cv.imshow('0', image)
    #cv.waitKey(0)# the number of windows
    image_with_MinRect=image
    return image_with_MinRect
def Binary(image):
    # for binary type, donot need :MaxvalMaxval=conf.getint('Binary', 'value')# set to be that value, 
    return_value,image_Binary=cv2.threshold(image,127,255,cv2.THRESH_BINARY_INV)
    return image_Binary



img = cv2.imread("./image_preprocess/char_seg.jpg",)  
path='./image_preprocess/'

image_Guass=cv2.GaussianBlur(img, (5, 5), 2)
iamge_Gary=cv2.cvtColor(image_Guass, cv2.COLOR_BGR2GRAY)
image_Binary=Binary(iamge_Gary)

save_image(image_Binary,'image_Binary')





#gray_lap = cv2.Laplacian(img,cv2.CV_16S,ksize = 3)

#dst = cv2.convertScaleAbs(gray_lap) 
#save_image(dst,"dst")


#image_Edge,contours=Edge('./image_preprocess/dst.jpg')

#image_with_MinRect=draw_Min_Rect(img,contours)

